///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AddAnalyst
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AddAnalystRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d7495c70-89cf-474a-af6e-afdd27af1f82")]
    public partial class AddAnalystRepository : RepoGenBaseFolder
    {
        static AddAnalystRepository instance = new AddAnalystRepository();
        AddAnalystRepositoryFolders.ARchitectLoginAppFolder _architectlogin;
        AddAnalystRepositoryFolders.DashboardAppFolder _dashboard;
        AddAnalystRepositoryFolders.ExplorerAppFolder _explorer;
        AddAnalystRepositoryFolders.Explorer1AppFolder _explorer1;
        AddAnalystRepositoryFolders.DropdownAppFolder _dropdown;

        /// <summary>
        /// Gets the singleton class instance representing the AddAnalystRepository element repository.
        /// </summary>
        [RepositoryFolder("d7495c70-89cf-474a-af6e-afdd27af1f82")]
        public static AddAnalystRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AddAnalystRepository() 
            : base("AddAnalystRepository", "/", null, 0, false, "d7495c70-89cf-474a-af6e-afdd27af1f82", ".\\RepositoryImages\\AddAnalystRepositoryd7495c70.rximgres")
        {
            _architectlogin = new AddAnalystRepositoryFolders.ARchitectLoginAppFolder(this);
            _dashboard = new AddAnalystRepositoryFolders.DashboardAppFolder(this);
            _explorer = new AddAnalystRepositoryFolders.ExplorerAppFolder(this);
            _explorer1 = new AddAnalystRepositoryFolders.Explorer1AppFolder(this);
            _dropdown = new AddAnalystRepositoryFolders.DropdownAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d7495c70-89cf-474a-af6e-afdd27af1f82")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ARchitectLogin folder.
        /// </summary>
        [RepositoryFolder("0ebbfb86-efea-4718-9273-1537b863a27b")]
        public virtual AddAnalystRepositoryFolders.ARchitectLoginAppFolder ARchitectLogin
        {
            get { return _architectlogin; }
        }

        /// <summary>
        /// The Dashboard folder.
        /// </summary>
        [RepositoryFolder("4e76e530-55e4-4608-b431-1772403e952a")]
        public virtual AddAnalystRepositoryFolders.DashboardAppFolder Dashboard
        {
            get { return _dashboard; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("abb066b6-a7f6-4ad0-baf0-5b3c037677b4")]
        public virtual AddAnalystRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("7aeccc7e-16d5-49c2-8498-44ac4b3d20c0")]
        public virtual AddAnalystRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("97325412-e45b-4427-b84b-0333ffc4693b")]
        public virtual AddAnalystRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AddAnalystRepositoryFolders
    {
        /// <summary>
        /// The ARchitectLoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("0ebbfb86-efea-4718-9273-1537b863a27b")]
        public partial class ARchitectLoginAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _passwordInfo;

            /// <summary>
            /// Creates a new ARchitectLogin  folder.
            /// </summary>
            public ARchitectLoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ARchitectLogin", "/dom[@domain='securedev.arinsights.net']", parentFolder, 30000, null, false, "0ebbfb86-efea-4718-9273-1537b863a27b", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'Username']", ".//input[#'Username']", 38700, null, "2f80afb0-749e-4f73-8e46-eae086018fb7");
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//form[#'loginForm']//button[@innertext='Log in']", ".//form[#'loginForm']//button[@innertext='Log in']", 38700, null, "3940a1fe-f2fa-48eb-ac3e-9352ad65c88a");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'Password']", ".//input[#'Password']", 38700, null, "88267c56-ad03-481d-84ae-ccebfb75bb4b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0ebbfb86-efea-4718-9273-1537b863a27b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0ebbfb86-efea-4718-9273-1537b863a27b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("2f80afb0-749e-4f73-8e46-eae086018fb7")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("2f80afb0-749e-4f73-8e46-eae086018fb7")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("3940a1fe-f2fa-48eb-ac3e-9352ad65c88a")]
            public virtual Ranorex.ButtonTag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("3940a1fe-f2fa-48eb-ac3e-9352ad65c88a")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("88267c56-ad03-481d-84ae-ccebfb75bb4b")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("88267c56-ad03-481d-84ae-ccebfb75bb4b")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }
        }

        /// <summary>
        /// The DashboardAppFolder folder.
        /// </summary>
        [RepositoryFolder("4e76e530-55e4-4608-b431-1772403e952a")]
        public partial class DashboardAppFolder : RepoGenBaseFolder
        {
            AddAnalystRepositoryFolders.MphCphDivUpdateFolder _mphcphdivupdate;
            RepoItemInfo _mphcphddltypeInfo;
            RepoItemInfo _firmvirtualInfo;
            RepoItemInfo _mphcphtxtemailInfo;
            RepoItemInfo _mphcphtxttitleInfo;
            RepoItemInfo _analystsInfo;
            RepoItemInfo _searchfordummylastdummyfirstInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _mphcphtxtfirstnameInfo;
            RepoItemInfo _form1Info;
            RepoItemInfo _dummylastdummyfirstfirmvirtualInfo;
            RepoItemInfo _dummyfirstdummylastInfo;

            /// <summary>
            /// Creates a new Dashboard  folder.
            /// </summary>
            public DashboardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dashboard", "/dom[@domain='dev.arinsights.net']", parentFolder, 30000, null, false, "4e76e530-55e4-4608-b431-1772403e952a", "")
            {
                _mphcphdivupdate = new AddAnalystRepositoryFolders.MphCphDivUpdateFolder(this);
                _mphcphddltypeInfo = new RepoItemInfo(this, "MphCphDdlType", ".//select[#'mph_cph_ddlType']", ".//select[#'mph_cph_ddlType']", 38700, null, "0fb782f7-08b9-4a8e-ae98-07818cb468e5");
                _firmvirtualInfo = new RepoItemInfo(this, "FirmVirtual", ".//body[#'theBody']//a[@innertext='Firm Virtual']", ".//body[#'theBody']//a[@innertext='Firm Virtual']", 38700, null, "f49bce1b-1200-444d-89fe-4897baaf7bc4");
                _mphcphtxtemailInfo = new RepoItemInfo(this, "MphCphTxtEmail", ".//input[#'mph_cph_txtEmail']", ".//input[#'mph_cph_txtEmail']", 38700, null, "e955f98a-61f5-4037-821b-58a1ee0e5884");
                _mphcphtxttitleInfo = new RepoItemInfo(this, "MphCphTxtTitle", ".//input[#'mph_cph_txtTitle']", ".//input[#'mph_cph_txtTitle']", 38700, null, "29650436-a221-405f-ace9-9b2de1fea657");
                _analystsInfo = new RepoItemInfo(this, "Analysts", ".//ul[#'menuBarAN']/?/?/a[@innertext='Analysts']", ".//ul[#'menuBarAN']/?/?/a[@innertext='Analysts']", 38700, null, "1ce82da8-b6c8-496c-ba3f-fd16065ee320");
                _searchfordummylastdummyfirstInfo = new RepoItemInfo(this, "SearchForDummyLastDummyFirst", ".//body[#'theBody']//a[@innertext>'DummyLast, Dum']", ".//body[#'theBody']//a[@innertext>'Search for DummyLast, Dum']", 38700, null, "0654d5a6-5ea0-4ae0-8534-6bee41c96250");
                _logoutInfo = new RepoItemInfo(this, "LogOut", ".//div[#'toolBar']//a[@innertext='Log out']", ".//div[#'toolBar']//a[@innertext='Log out']", 38700, null, "fef1d481-48c9-4a4a-a78f-3c674cbd272f");
                _mphcphtxtfirstnameInfo = new RepoItemInfo(this, "MphCphTxtFirstName", ".//input[#'mph_cph_txtFirstName']", ".//input[#'mph_cph_txtFirstName']", 38700, null, "d0dd3034-7a95-4ba3-8e76-491ea88d2a53");
                _form1Info = new RepoItemInfo(this, "Form1", ".//form[#'form1']", ".//form[#'form1']", 38700, null, "e1be2679-d5bb-4ca7-8289-5553b2c221a3");
                _dummylastdummyfirstfirmvirtualInfo = new RepoItemInfo(this, "DummyLastDummyFirstFirmVirtual", ".//body[#'theBody']//a[@innertext>'DummyLast, DummyFirst - Firm']", ".//body[#'theBody']//a[@innertext>'DummyLast, DummyFirst - Firm']", 38700, null, "03dd0e71-44ba-480c-94bc-e78a3ad38a98");
                _dummyfirstdummylastInfo = new RepoItemInfo(this, "DummyFirstDummyLast", ".//div[#'mph_cph_ucFinderGrid_kGrid']//td[@innertext='DummyFirst DummyLast']", ".//div[#'mph_cph_ucFinderGrid_kGrid']//td[@innertext='DummyFirst DummyLast']", 38700, null, "80f69ba0-1a79-4c42-9af7-f59047a29a14");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4e76e530-55e4-4608-b431-1772403e952a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4e76e530-55e4-4608-b431-1772403e952a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MphCphDdlType item.
            /// </summary>
            [RepositoryItem("0fb782f7-08b9-4a8e-ae98-07818cb468e5")]
            public virtual Ranorex.SelectTag MphCphDdlType
            {
                get
                {
                    return _mphcphddltypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The MphCphDdlType item info.
            /// </summary>
            [RepositoryItemInfo("0fb782f7-08b9-4a8e-ae98-07818cb468e5")]
            public virtual RepoItemInfo MphCphDdlTypeInfo
            {
                get
                {
                    return _mphcphddltypeInfo;
                }
            }

            /// <summary>
            /// The FirmVirtual item.
            /// </summary>
            [RepositoryItem("f49bce1b-1200-444d-89fe-4897baaf7bc4")]
            public virtual Ranorex.ATag FirmVirtual
            {
                get
                {
                    return _firmvirtualInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FirmVirtual item info.
            /// </summary>
            [RepositoryItemInfo("f49bce1b-1200-444d-89fe-4897baaf7bc4")]
            public virtual RepoItemInfo FirmVirtualInfo
            {
                get
                {
                    return _firmvirtualInfo;
                }
            }

            /// <summary>
            /// The MphCphTxtEmail item.
            /// </summary>
            [RepositoryItem("e955f98a-61f5-4037-821b-58a1ee0e5884")]
            public virtual Ranorex.InputTag MphCphTxtEmail
            {
                get
                {
                    return _mphcphtxtemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The MphCphTxtEmail item info.
            /// </summary>
            [RepositoryItemInfo("e955f98a-61f5-4037-821b-58a1ee0e5884")]
            public virtual RepoItemInfo MphCphTxtEmailInfo
            {
                get
                {
                    return _mphcphtxtemailInfo;
                }
            }

            /// <summary>
            /// The MphCphTxtTitle item.
            /// </summary>
            [RepositoryItem("29650436-a221-405f-ace9-9b2de1fea657")]
            public virtual Ranorex.InputTag MphCphTxtTitle
            {
                get
                {
                    return _mphcphtxttitleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The MphCphTxtTitle item info.
            /// </summary>
            [RepositoryItemInfo("29650436-a221-405f-ace9-9b2de1fea657")]
            public virtual RepoItemInfo MphCphTxtTitleInfo
            {
                get
                {
                    return _mphcphtxttitleInfo;
                }
            }

            /// <summary>
            /// The Analysts item.
            /// </summary>
            [RepositoryItem("1ce82da8-b6c8-496c-ba3f-fd16065ee320")]
            public virtual Ranorex.ATag Analysts
            {
                get
                {
                    return _analystsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Analysts item info.
            /// </summary>
            [RepositoryItemInfo("1ce82da8-b6c8-496c-ba3f-fd16065ee320")]
            public virtual RepoItemInfo AnalystsInfo
            {
                get
                {
                    return _analystsInfo;
                }
            }

            /// <summary>
            /// The SearchForDummyLastDummyFirst item.
            /// </summary>
            [RepositoryItem("0654d5a6-5ea0-4ae0-8534-6bee41c96250")]
            public virtual Ranorex.ATag SearchForDummyLastDummyFirst
            {
                get
                {
                    return _searchfordummylastdummyfirstInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SearchForDummyLastDummyFirst item info.
            /// </summary>
            [RepositoryItemInfo("0654d5a6-5ea0-4ae0-8534-6bee41c96250")]
            public virtual RepoItemInfo SearchForDummyLastDummyFirstInfo
            {
                get
                {
                    return _searchfordummylastdummyfirstInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("fef1d481-48c9-4a4a-a78f-3c674cbd272f")]
            public virtual Ranorex.ATag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("fef1d481-48c9-4a4a-a78f-3c674cbd272f")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The MphCphTxtFirstName item.
            /// </summary>
            [RepositoryItem("d0dd3034-7a95-4ba3-8e76-491ea88d2a53")]
            public virtual Ranorex.InputTag MphCphTxtFirstName
            {
                get
                {
                    return _mphcphtxtfirstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The MphCphTxtFirstName item info.
            /// </summary>
            [RepositoryItemInfo("d0dd3034-7a95-4ba3-8e76-491ea88d2a53")]
            public virtual RepoItemInfo MphCphTxtFirstNameInfo
            {
                get
                {
                    return _mphcphtxtfirstnameInfo;
                }
            }

            /// <summary>
            /// The Form1 item.
            /// </summary>
            [RepositoryItem("e1be2679-d5bb-4ca7-8289-5553b2c221a3")]
            public virtual Ranorex.FormTag Form1
            {
                get
                {
                    return _form1Info.CreateAdapter<Ranorex.FormTag>(true);
                }
            }

            /// <summary>
            /// The Form1 item info.
            /// </summary>
            [RepositoryItemInfo("e1be2679-d5bb-4ca7-8289-5553b2c221a3")]
            public virtual RepoItemInfo Form1Info
            {
                get
                {
                    return _form1Info;
                }
            }

            /// <summary>
            /// The DummyLastDummyFirstFirmVirtual item.
            /// </summary>
            [RepositoryItem("03dd0e71-44ba-480c-94bc-e78a3ad38a98")]
            public virtual Ranorex.ATag DummyLastDummyFirstFirmVirtual
            {
                get
                {
                    return _dummylastdummyfirstfirmvirtualInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DummyLastDummyFirstFirmVirtual item info.
            /// </summary>
            [RepositoryItemInfo("03dd0e71-44ba-480c-94bc-e78a3ad38a98")]
            public virtual RepoItemInfo DummyLastDummyFirstFirmVirtualInfo
            {
                get
                {
                    return _dummylastdummyfirstfirmvirtualInfo;
                }
            }

            /// <summary>
            /// The DummyFirstDummyLast item.
            /// </summary>
            [RepositoryItem("80f69ba0-1a79-4c42-9af7-f59047a29a14")]
            public virtual Ranorex.TdTag DummyFirstDummyLast
            {
                get
                {
                    return _dummyfirstdummylastInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The DummyFirstDummyLast item info.
            /// </summary>
            [RepositoryItemInfo("80f69ba0-1a79-4c42-9af7-f59047a29a14")]
            public virtual RepoItemInfo DummyFirstDummyLastInfo
            {
                get
                {
                    return _dummyfirstdummylastInfo;
                }
            }

            /// <summary>
            /// The MphCphDivUpdate folder.
            /// </summary>
            [RepositoryFolder("36e743be-a795-49ea-9e95-4b160127948a")]
            public virtual AddAnalystRepositoryFolders.MphCphDivUpdateFolder MphCphDivUpdate
            {
                get { return _mphcphdivupdate; }
            }
        }

        /// <summary>
        /// The MphCphDivUpdateFolder folder.
        /// </summary>
        [RepositoryFolder("36e743be-a795-49ea-9e95-4b160127948a")]
        public partial class MphCphDivUpdateFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ctl00dollarctl00dollarmphdollarcphdollarInfo;
            RepoItemInfo _save1Info;
            RepoItemInfo _saveInfo;

            /// <summary>
            /// Creates a new MphCphDivUpdate  folder.
            /// </summary>
            public MphCphDivUpdateFolder(RepoGenBaseFolder parentFolder) :
                    base("MphCphDivUpdate", ".//div[#'mph_cph_divUpdate']", parentFolder, 30000, null, false, "36e743be-a795-49ea-9e95-4b160127948a", "")
            {
                _ctl00dollarctl00dollarmphdollarcphdollarInfo = new RepoItemInfo(this, "Ctl00Dollarctl00DollarmphDollarcphDollar", ".//input[@name='ctl00$ctl00$mph$cph$ucACTextBox1$txtAC']", ".//input[@name='ctl00$ctl00$mph$cph$ucACTextBox1$txtAC']", 38700, null, "a83f34da-493d-4a63-aaec-c5417841225f");
                _save1Info = new RepoItemInfo(this, "Save1", "div[1]/div/a[@innertext='Save']", "div[1]/div/a[@innertext='Save']", 38700, null, "dcc90432-0cf9-430c-a082-659e6896b350");
                _saveInfo = new RepoItemInfo(this, "Save", "div[7]/a[@innertext='Save']", "div[7]/a[@innertext='Save']", 38700, null, "e90e188c-7cd7-4a9b-bd9e-147cc272cccd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("36e743be-a795-49ea-9e95-4b160127948a")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("36e743be-a795-49ea-9e95-4b160127948a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Ctl00Dollarctl00DollarmphDollarcphDollar item.
            /// </summary>
            [RepositoryItem("a83f34da-493d-4a63-aaec-c5417841225f")]
            public virtual Ranorex.InputTag Ctl00Dollarctl00DollarmphDollarcphDollar
            {
                get
                {
                    return _ctl00dollarctl00dollarmphdollarcphdollarInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Ctl00Dollarctl00DollarmphDollarcphDollar item info.
            /// </summary>
            [RepositoryItemInfo("a83f34da-493d-4a63-aaec-c5417841225f")]
            public virtual RepoItemInfo Ctl00Dollarctl00DollarmphDollarcphDollarInfo
            {
                get
                {
                    return _ctl00dollarctl00dollarmphdollarcphdollarInfo;
                }
            }

            /// <summary>
            /// The Save1 item.
            /// </summary>
            [RepositoryItem("dcc90432-0cf9-430c-a082-659e6896b350")]
            public virtual Ranorex.ATag Save1
            {
                get
                {
                    return _save1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Save1 item info.
            /// </summary>
            [RepositoryItemInfo("dcc90432-0cf9-430c-a082-659e6896b350")]
            public virtual RepoItemInfo Save1Info
            {
                get
                {
                    return _save1Info;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("e90e188c-7cd7-4a9b-bd9e-147cc272cccd")]
            public virtual Ranorex.ATag Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("e90e188c-7cd7-4a9b-bd9e-147cc272cccd")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("abb066b6-a7f6-4ad0-baf0-5b3c037677b4")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ranorexstudio2runningwindowsInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "abb066b6-a7f6-4ad0-baf0-5b3c037677b4", "")
            {
                _ranorexstudio2runningwindowsInfo = new RepoItemInfo(this, "RanorexStudio2RunningWindows", ".//toolbar[@accessiblename='Running applications']/button[12]", ".//toolbar[@accessiblename='Running applications']/button[12]", 38700, null, "ba740b55-0554-423f-b225-35726f92e80a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("abb066b6-a7f6-4ad0-baf0-5b3c037677b4")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("abb066b6-a7f6-4ad0-baf0-5b3c037677b4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RanorexStudio2RunningWindows item.
            /// </summary>
            [RepositoryItem("ba740b55-0554-423f-b225-35726f92e80a")]
            public virtual Ranorex.Button RanorexStudio2RunningWindows
            {
                get
                {
                    return _ranorexstudio2runningwindowsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RanorexStudio2RunningWindows item info.
            /// </summary>
            [RepositoryItemInfo("ba740b55-0554-423f-b225-35726f92e80a")]
            public virtual RepoItemInfo RanorexStudio2RunningWindowsInfo
            {
                get
                {
                    return _ranorexstudio2runningwindowsInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("7aeccc7e-16d5-49c2-8498-44ac4b3d20c0")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addanalystranorexstudio32bitaInfo;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/form[@title='']", parentFolder, 30000, null, true, "7aeccc7e-16d5-49c2-8498-44ac4b3d20c0", "")
            {
                _addanalystranorexstudio32bitaInfo = new RepoItemInfo(this, "AddAnalystRanorexStudio32bitA", "?/?/listitem[@accessiblename>'AddAnalyst - Ranorex Studio']", "?/?/listitem[@accessiblename>'AddAnalyst - Ranorex Studio']", 38700, null, "12b5856c-fd24-4610-ab22-25c6440a5ccc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7aeccc7e-16d5-49c2-8498-44ac4b3d20c0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7aeccc7e-16d5-49c2-8498-44ac4b3d20c0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddAnalystRanorexStudio32bitA item.
            /// </summary>
            [RepositoryItem("12b5856c-fd24-4610-ab22-25c6440a5ccc")]
            public virtual Ranorex.ListItem AddAnalystRanorexStudio32bitA
            {
                get
                {
                    return _addanalystranorexstudio32bitaInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The AddAnalystRanorexStudio32bitA item info.
            /// </summary>
            [RepositoryItemInfo("12b5856c-fd24-4610-ab22-25c6440a5ccc")]
            public virtual RepoItemInfo AddAnalystRanorexStudio32bitAInfo
            {
                get
                {
                    return _addanalystranorexstudio32bitaInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("97325412-e45b-4427-b84b-0333ffc4693b")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "97325412-e45b-4427-b84b-0333ffc4693b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("97325412-e45b-4427-b84b-0333ffc4693b")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("97325412-e45b-4427-b84b-0333ffc4693b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
