///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AddAnalyst
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddAnalyst recording.
    /// </summary>
    [TestModule("301c8ce7-bbc3-4b96-a60f-04a41a28deff", ModuleType.Recording, 1)]
    public partial class AddAnalyst : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AddAnalystRepository repository.
        /// </summary>
        public static AddAnalystRepository repo = AddAnalystRepository.Instance;

        static AddAnalyst instance = new AddAnalyst();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddAnalyst()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddAnalyst Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ARchitectLogin.Username' at 109;16.", repo.ARchitectLogin.UsernameInfo, new RecordItemIndex(0));
            repo.ARchitectLogin.Username.Click("109;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 12}' with focus on 'ARchitectLogin.Username'.", repo.ARchitectLogin.UsernameInfo, new RecordItemIndex(1));
            repo.ARchitectLogin.Username.PressKeys("{Back 12}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aritester' with focus on 'ARchitectLogin.Username'.", repo.ARchitectLogin.UsernameInfo, new RecordItemIndex(2));
            repo.ARchitectLogin.Username.PressKeys("aritester");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '27Jan2021' with focus on 'ARchitectLogin'.", repo.ARchitectLogin.SelfInfo, new RecordItemIndex(3));
            repo.ARchitectLogin.Self.EnsureVisible();
            Keyboard.Press("27Jan2021");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ARchitectLogin.LogIn' at 173;6.", repo.ARchitectLogin.LogInInfo, new RecordItemIndex(4));
            repo.ARchitectLogin.LogIn.Click("173;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard' at 525;177.", repo.Dashboard.SelfInfo, new RecordItemIndex(5));
            repo.Dashboard.Self.Click("525;177");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.MphCphTxtFirstName' at 39;2.", repo.Dashboard.MphCphTxtFirstNameInfo, new RecordItemIndex(6));
            repo.Dashboard.MphCphTxtFirstName.Click("39;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'DummyFirst' with focus on 'Dashboard.MphCphTxtFirstName'.", repo.Dashboard.MphCphTxtFirstNameInfo, new RecordItemIndex(7));
            repo.Dashboard.MphCphTxtFirstName.PressKeys("DummyFirst");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}{Tab}DummyLast{Tab}' with focus on 'Dashboard.MphCphTxtFirstName'.", repo.Dashboard.MphCphTxtFirstNameInfo, new RecordItemIndex(8));
            repo.Dashboard.MphCphTxtFirstName.PressKeys("{Tab}{Tab}DummyLast{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Dashboard'.", repo.Dashboard.SelfInfo, new RecordItemIndex(9));
            repo.Dashboard.Self.EnsureVisible();
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Dashboard'.", repo.Dashboard.SelfInfo, new RecordItemIndex(10));
            repo.Dashboard.Self.EnsureVisible();
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Analyst{RShiftKey down}_{RShiftKey up}Test{Tab}' with focus on 'Dashboard'.", repo.Dashboard.SelfInfo, new RecordItemIndex(11));
            repo.Dashboard.Self.EnsureVisible();
            Keyboard.Press("Analyst{RShiftKey down}_{RShiftKey up}Test{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '2' on item 'Dashboard.MphCphDdlType'.", repo.Dashboard.MphCphDdlTypeInfo, new RecordItemIndex(12));
            repo.Dashboard.MphCphDdlType.Element.SetAttributeValue("TagValue", "2");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.MphCphDivUpdate.Ctl00Dollarctl00DollarmphDollarcphDollar' at 95;5.", repo.Dashboard.MphCphDivUpdate.Ctl00Dollarctl00DollarmphDollarcphDollarInfo, new RecordItemIndex(13));
            repo.Dashboard.MphCphDivUpdate.Ctl00Dollarctl00DollarmphDollarcphDollar.Click("95;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Firm ' with focus on 'Dashboard.MphCphDivUpdate.Ctl00Dollarctl00DollarmphDollarcphDollar'.", repo.Dashboard.MphCphDivUpdate.Ctl00Dollarctl00DollarmphDollarcphDollarInfo, new RecordItemIndex(14));
            repo.Dashboard.MphCphDivUpdate.Ctl00Dollarctl00DollarmphDollarcphDollar.PressKeys("Firm ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.FirmVirtual' at 83;10.", repo.Dashboard.FirmVirtualInfo, new RecordItemIndex(15));
            repo.Dashboard.FirmVirtual.Click("83;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard' at 1152;272.", repo.Dashboard.SelfInfo, new RecordItemIndex(16));
            repo.Dashboard.Self.Click("1152;272");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 69;21.", repo.Dropdown.SelfInfo, new RecordItemIndex(17));
            repo.Dropdown.Self.Click("69;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.MphCphTxtEmail' at 142;14.", repo.Dashboard.MphCphTxtEmailInfo, new RecordItemIndex(18));
            repo.Dashboard.MphCphTxtEmail.Click("142;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1234' with focus on 'Dashboard.MphCphTxtEmail'.", repo.Dashboard.MphCphTxtEmailInfo, new RecordItemIndex(19));
            repo.Dashboard.MphCphTxtEmail.PressKeys("1234");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.MphCphDivUpdate.Save1' at 19;12.", repo.Dashboard.MphCphDivUpdate.Save1Info, new RecordItemIndex(20));
            repo.Dashboard.MphCphDivUpdate.Save1.Click("19;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard' at 579;244.", repo.Dashboard.SelfInfo, new RecordItemIndex(21));
            repo.Dashboard.Self.Click("579;244");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.Form1' at 700;208.", repo.Dashboard.Form1Info, new RecordItemIndex(22));
            repo.Dashboard.Form1.Click("700;208");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'DummyLast, DummyFirst' with focus on 'Dashboard'.", repo.Dashboard.SelfInfo, new RecordItemIndex(23));
            repo.Dashboard.Self.EnsureVisible();
            Keyboard.Press("DummyLast, DummyFirst");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.DummyLastDummyFirstFirmVirtual' at 100;11.", repo.Dashboard.DummyLastDummyFirstFirmVirtualInfo, new RecordItemIndex(24));
            repo.Dashboard.DummyLastDummyFirstFirmVirtual.Click("100;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.DummyFirstDummyLast' at 80;33.", repo.Dashboard.DummyFirstDummyLastInfo, new RecordItemIndex(25));
            repo.Dashboard.DummyFirstDummyLast.Click("80;33");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
