///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AddAnalyst
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyAnalyst recording.
    /// </summary>
    [TestModule("f4507655-7224-44bb-877b-74efea790153", ModuleType.Recording, 1)]
    public partial class VerifyAnalyst : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AddAnalystRepository repository.
        /// </summary>
        public static AddAnalystRepository repo = AddAnalystRepository.Instance;

        static VerifyAnalyst instance = new VerifyAnalyst();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyAnalyst()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyAnalyst Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.Analysts' at 53;11.", repo.Dashboard.AnalystsInfo, new RecordItemIndex(0));
            repo.Dashboard.Analysts.Click("53;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard' at 641;199.", repo.Dashboard.SelfInfo, new RecordItemIndex(1));
            repo.Dashboard.Self.Click("641;199");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'DummyLast, DummyFirst' with focus on 'Dashboard'.", repo.Dashboard.SelfInfo, new RecordItemIndex(2));
            repo.Dashboard.Self.EnsureVisible();
            Keyboard.Press("DummyLast, DummyFirst");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.SearchForDummyLastDummyFirst' at 53;13.", repo.Dashboard.SearchForDummyLastDummyFirstInfo, new RecordItemIndex(3));
            repo.Dashboard.SearchForDummyLastDummyFirst.Click("53;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dashboard.LogOut' at 17;18.", repo.Dashboard.LogOutInfo, new RecordItemIndex(4));
            repo.Dashboard.LogOut.Click("17;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.RanorexStudio2RunningWindows' at 28;24.", repo.Explorer.RanorexStudio2RunningWindowsInfo, new RecordItemIndex(5));
            repo.Explorer.RanorexStudio2RunningWindows.Click("28;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.AddAnalystRanorexStudio32bitA' at 116;14.", repo.Explorer1.AddAnalystRanorexStudio32bitAInfo, new RecordItemIndex(6));
            repo.Explorer1.AddAnalystRanorexStudio32bitA.Click("116;14");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
